### ISSUE TITLE
appium 是否实现CSS定位

### ISSUE THREAD

**Issue by 781412862** [defnngj/poium#7]
selenium.common.exceptions.WebDriverException: Message: Method is not implemented

请问appium是否实现使用CSSElement定位

**Comment by 781412862** [comment]
from poium import Page, PageElement,CSSElement
from appium import webdriver


class CalculatorPage(Page):
    inpt_1 = CSSElement("input[placeholder=\"请输入手机号\"]")
    inpt_2 = CSSElement("#login_password")
    add = CSSElement("#btn_login2mode")


# APP定义运行环境
desired_caps = {

}
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

page = CalculatorPage(driver)
page.inpt_1.click()
page.inpt_2.click()
page.add.click()
driver.quit()

**Comment by defnngj** [comment]
appium 不支持 ``` find_element_by_css_selector()``` 定位， 在App中是通过布局文件（xml）来实现界面，web是通过HTML实现的页面，两者本身存在差异，所以，App不支持CSS语法的定位。
