### ISSUE TITLE
你好，查找的元素需要确定index怎么传参

### ISSUE THREAD

**Issue by 781412862** [defnngj/poium#8]
这是不用poium获取方式
driver.find_elements_by_android_uiautomator('new UiSelector().className(\"android.widget.Button\")‘)[2].click()

使用poium如果这样写
login = PageElement(android_uiautomator='new UiSelector().className(\"android.widget.Button\")‘)

只能获取到第一个，如果我先传入index获取第二个，需要怎么传参呢

**Comment by 781412862** [comment]
如果这样写：
login = PageElement(android_uiautomator="new UiSelector().className(\"android.widget.Button\")[2]")
报错：
selenium.common.exceptions.WebDriverException: Message: Could not parse UiSelector argument: Expected "." but saw "["

**Comment by 781412862** [comment]
哪位大哥能帮我看下吗，卡在这里了。

**Comment by defnngj** [comment]
使用 ```PageElements```获取一组元素
```python
login = PageElements(android_uiautomator='new UiSelector().className("android.widget.Button")')[1]
```
注意单、双引号的使用

* [0] 表示返回一组定位元素当中的第一个
* [1] 表示返回一组定位元素当中的第二个

**Comment by 781412862** [comment]
这样使用会报错。
login = PageElements(android_uiautomator='new UiSelector().className("android.widget.Button")')[2]
提示
TypeError: 'PageElements' object does not support indexing

**Comment by defnngj** [comment]
抱歉，用法是这样的：

```python
from poium import Page, PageElements


class xxxPage(Page):
    login = PageElements(android_uiautomator='new UiSelector().className("android.widget.Button")')

……

page.login[0].send_keys("poium")


```
* [0] 表示返回一组定位元素当中的第一个
* [1] 表示返回一组定位元素当中的第二个

**Comment by 781412862** [comment]
可以了，完美解决问题，谢谢老哥
